# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20151202_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Group')], default=0),
        ),
        migrations.AddField(
            model_name='invitation',
            name='subject_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
